### ISSUE TITLE
Add targeting labels to Intro/Non Intro modules, Appendices

### ISSUE THREAD

**Issue by ajluk** [openstax/cookbook#22]
Link to the documentation: https://docs.google.com/document/d/1_LjLkeY-9ZkDBvMU1Je7S0AaVOTak37xT0J8pFd3H4E/edit
Related cnx-recipes issue: https://github.com/openstax/cnx-recipes/issues/4430

**Comment by ajluk** [comment]
@MartaSztuka Information for testing purposes: Link to github page containing the `texting-anchor` book: `https://github.com/openstax/osbooks-ce-styles-test/testing-anchor` recipe: `testing-anchor`
Screnshot for reference showing how the marked linkes should look like:
![image](https://user-images.githubusercontent.com/55203598/155992920-b4225382-5567-463b-9d2a-aefd9894b7f0.png)

**Comment by MartaSztuka** [comment]
#### PASSED
##### Testing Anchor
![Screenshot from 2022-02-28 16-03-48](https://user-images.githubusercontent.com/47241114/156006163-4cd66cea-c6b6-4f56-ad10-3ed19692a745.png)
##### Accounting 1
![Screenshot from 2022-02-28 16-12-55](https://user-images.githubusercontent.com/47241114/156007598-731e0ab8-d27c-4677-8dd0-8257b176432b.png)
##### Accounting 2
![Screenshot from 2022-02-28 16-22-18](https://user-images.githubusercontent.com/47241114/156009115-30572d8c-1cd1-4c5d-ab97-42f8b9e851a1.png)
